apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myweb-rs
spec:
  replicas: 5
  selector:
    matchLabels:
      env: dev
#    matchExpressions:
#      - { key: env, operator: In, values: [dev] }
#      - { key: location, operator: In, values: [India] }
  template:
    metadata:
     name: web-pod
     labels:
       env: dev
    spec:
      containers:
      - name: web-con
        image: raktim00/httpd:v1
