apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
#    matchExpressions:
#      - { key: env, operator: In, values: [dev] }
#      - { key: location, operator: In, values: [India] }
  template:
    metadata:
     name: web-pod
     labels:
       env: dev
    spec:
      containers:
      - name: web-con
        image: raktim00/httpd:v1